### ISSUE TITLE
program deleted my movies folder

### ISSUE THREAD

**Issue by who-is-nobody** [MiyukiQAQ/MissAV-Downloader#12]
im using mac m1 
I typed miyuki -urls "example_url" -ffmpeg
and my movies folder is just gone
i lost more than 20gbs of files
can you tell my why my files got deleted?

**Comment by MiyukiQAQ** [comment]
sorry ， movies is the default download directory. After downloading, the temporary folder in movies will be cleared. I should change the name of movies to something less generic.

**Comment by MiyukiQAQ** [comment]
Normally miyuki will only delete subfolders in the movies folder at the same level as the miyuki command.

**Comment by who-is-nobody** [comment]
Thanks, i had a backup so it was a bit annoying but ok.
But i still don't understand why my movies were detected as a 'temporary folder'

**Comment by MiyukiQAQ** [comment]
> Thanks, i had a backup so it was a bit annoying but ok.
> 
> But i still don't understand why my movies were detected as a 'temporary folder'

A video is composed of many segments. If I want to download a video named ABC, miyuki will first create a movies folder in the same directory as the miyuki command (now changed to miyuki_movies_folder), and then create an ABC folder in the movies folder. All the segments of the ABC video will be saved in the ABC folder. After the segments are downloaded, the segments will be combined into a video and saved in the movies folder. So when the video is combined, the ABC folder is no longer useful, and miyuki will delete the ABC folder under the movies folder. All folders under the movies folder are considered temporary directories.
