### ISSUE TITLE
Single actress

### ISSUE THREAD

**Issue by Deyusha69** [MiyukiQAQ/MissAV-Downloader#13]
hi the script work well thank you. can you add only single actress like this https://missav.com/dm132/en/actresses/Julia?filters=individual

**Comment by MiyukiQAQ** [comment]
> hi the script work well thank you. can you add only single actress like this https://missav.com/dm132/en/actresses/Julia?filters=individual

try this url with -plist parameter

**Comment by Deyusha69** [comment]
thank you it's working. i try a while ago and not working i think i type wrong command

**Comment by MiyukiQAQ** [comment]
> thank you it's working. i try a while ago and not working i think i type wrong command

There is a bug here, it seems that miyuki will only download the first page of content, because of the page turning there will be an error, I will fix it tonight.
