### ISSUE TITLE
Modify download address and download cover

### ISSUE THREAD

**Issue by iloveguodegang** [MiyukiQAQ/MissAV-Downloader#15]
Can you add the function of modifying the download address and downloading the cover?

**Comment by MiyukiQAQ** [comment]
What does "modifying the download address" mean? Customize the folder where videos are downloaded? The function of downloading cover can be added later.

**Comment by iloveguodegang** [comment]
Here is the translation of your request:

"Currently, downloaded files are saved directly to the 'C:\miyuki_movies_folder' folder on my C drive. This makes it difficult to download multiple files because my C drive has limited storage space. 
If add an option like `-d folder_path` to specify the download directory is better

**Comment by iloveguodegang** [comment]
Now downloaded files are saved directly to the 'C:\miyuki_movies_folder' folder on my C drive. This makes it difficult to download multiple files because my C drive has limited storage space. 
I think if add an option like  -d folder_path   to specify the download directory is better

**Comment by MiyukiQAQ** [comment]
> Now downloaded files are saved directly to the 'C:\miyuki_movies_folder' folder on my C drive. This makes it difficult to download multiple files because my C drive has limited storage space. I think if add an option like -d folder_path to specify the download directory is better

In which directory you run the miyuki command, the miyuki_movies_folder folder will be created in that directory. But I think your suggestion is also good, I will implement this.

**Comment by iloveguodegang** [comment]
Thank you, I will masturbate one more time for you.

**Comment by MiyukiQAQ** [comment]
> Thank you, I will masturbate one more time for you.

You can now use the -cover parameter to save the cover when downloading videos. For details, please see the readme. You need to upgrade miyuki first, use pip install --upgrade miyuki
