### ISSUE TITLE
Added the tagging function for actress

### ISSUE THREAD

**Issue by hydrogen1222** [MiyukiQAQ/MissAV-Downloader#16]
What I mean is that an actress's work may have a lot of tags and genres, could you  please add tags so that you can only download a certain type of movie for a certain actor, such as JULIA's solo movie

THANKS A LOT！

**Comment by MiyukiQAQ** [comment]
You can filter the conditions on the web page first, then directly copy the web page URL and try using the -plist parameter.
#13

**Comment by MiyukiQAQ** [comment]
> What I mean is that an actress's work may have a lot of tags and genres, could you please add tags so that you can only download a certain type of movie for a certain actor, such as JULIA's solo movie
> 
> THANKS A LOT！

Basically, as long as it is a "page that can be turned", you can use the -plist parameter. For example, if you search for something, you will enter a "page that can be turned", click on an actress or click on a tag to enter a "page that can be turned", and so on. You just need to copy the URL of that page and use the -plist parameter. I don't know if I'm clear enough. By the way, I also like JULIA very much

**Comment by hydrogen1222** [comment]
> > What I mean is that an actress's work may have a lot of tags and genres, could you please add tags so that you can only download a certain type of movie for a certain actor, such as JULIA's solo movie
> > THANKS A LOT！
> 
> Basically, as long as it is a "page that can be turned", you can use the -plist parameter. For example, if you search for something, you will enter a "page that can be turned", click on an actress or click on a tag to enter a "page that can be turned", and so on. You just need to copy the URL of that page and use the -plist parameter. I don't know if I'm clear enough. By the way, I also like JULIA very much

I'm trying but face some problems.What is your contact information like wechat ?

**Comment by MiyukiQAQ** [comment]
![ig](https://github.com/user-attachments/assets/48752816-9fbd-4f72-9bfb-48df76fa84bc)
![tg](https://github.com/user-attachments/assets/72bf6fb7-122e-40fd-9716-2138968d7c4e)

Telegram & Instagram

> > > What I mean is that an actress's work may have a lot of tags and genres, could you please add tags so that you can only download a certain type of movie for a certain actor, such as JULIA's solo movie
> > > THANKS A LOT！
> > 
> > 
> > Basically, as long as it is a "page that can be turned", you can use the -plist parameter. For example, if you search for something, you will enter a "page that can be turned", click on an actress or click on a tag to enter a "page that can be turned", and so on. You just need to copy the URL of that page and use the -plist parameter. I don't know if I'm clear enough. By the way, I also like JULIA very much
> 
> I'm trying but face some problems.What is your contact information like wechat ?

**Comment by MiyukiQAQ** [comment]
> > > What I mean is that an actress's work may have a lot of tags and genres, could you please add tags so that you can only download a certain type of movie for a certain actor, such as JULIA's solo movie
> > > THANKS A LOT！
> > 
> > 
> > Basically, as long as it is a "page that can be turned", you can use the -plist parameter. For example, if you search for something, you will enter a "page that can be turned", click on an actress or click on a tag to enter a "page that can be turned", and so on. You just need to copy the URL of that page and use the -plist parameter. I don't know if I'm clear enough. By the way, I also like JULIA very much
> 
> I'm trying but face some problems.What is your contact information like wechat ?

You can try to look at the description of -plist in the readme, which I updated last night.

**Comment by MiyukiQAQ** [comment]
> > > What I mean is that an actress's work may have a lot of tags and genres, could you please add tags so that you can only download a certain type of movie for a certain actor, such as JULIA's solo movie
> > > THANKS A LOT！
> > 
> > 
> > Basically, as long as it is a "page that can be turned", you can use the -plist parameter. For example, if you search for something, you will enter a "page that can be turned", click on an actress or click on a tag to enter a "page that can be turned", and so on. You just need to copy the URL of that page and use the -plist parameter. I don't know if I'm clear enough. By the way, I also like JULIA very much
> 
> I'm trying but face some problems.What is your contact information like wechat ?

I might know what you want to say.
URLs with & symbols will fail to turn pages

**Comment by hydrogen1222** [comment]
> > > > What I mean is that an actress's work may have a lot of tags and genres, could you please add tags so that you can only download a certain type of movie for a certain actor, such as JULIA's solo movie我的意思是，一个女演员的作品可能有很多标签和类型，你能不能添加标签，这样你只能为某个演员下载某种类型的电影，比如JULIA的个人电影
> > > > THANKS A LOT！   非常感谢!
> > > 
> > > 
> > > Basically, as long as it is a "page that can be turned", you can use the -plist parameter. For example, if you search for something, you will enter a "page that can be turned", click on an actress or click on a tag to enter a "page that can be turned", and so on. You just need to copy the URL of that page and use the -plist parameter. I don't know if I'm clear enough. By the way, I also like JULIA very much基本上，只要是“可以翻页的页面”，就可以使用-plist参数。例如，如果你搜索某样东西，你会输入一个“可以翻页的页面”，点击一个女演员或点击一个标签来进入一个“可以翻页的页面”，等等。您只需要复制该页的URL并使用-plist参数。我不知道我是否说得够清楚。顺便说一下，我也很喜欢JULIA
> > 
> > 
> > I'm trying but face some problems.What is your contact information like wechat ?我在努力，但面临一些问题。你的微信联系方式是什么?
> 
> I might know what you want to say.我可能知道你想说什么。 URLs with & symbols will fail to turn pages带有&符号的url将无法翻页

I texted you on Instagram
