### ISSUE TITLE
feature request: add a optional parameter to use a file as input

### ISSUE THREAD

**Issue by NTFSvolume** [MiyukiQAQ/MissAV-Downloader#20]
Each line in the file will be an URL

Useful when downloading a large number of videos. 

This also prevents hitting the 4096 characters limit for a command.

Suggested argparse argument: `-file`

**Comment by MiyukiQAQ** [comment]
> Each line in the file will be an URL
> 
> Useful when downloading a large number of videos.
> 
> This also prevents hitting the 4096 characters limit for a command.
> 
> Suggested argparse argument: `-file`

Done, you need to upgrade miyuki to use the -file parameter
