### ISSUE TITLE
Log error/failed urls and grab English title

### ISSUE THREAD

**Issue by snwefly** [MiyukiQAQ/MissAV-Downloader#21]
First of all Thanks for the application, its working wonderfully.

Is there any way to log error/failed urls to text file?

Also could you please add a way to grab the English title as suffix to the video filename?

Thanks

**Comment by MiyukiQAQ** [comment]
> First of all Thanks for the application, its working wonderfully.
> 
> Is there any way to log error/failed urls to text file?
> 
> Also could you please add a way to grab the English title as suffix to the video filename?
> 
> Thanks

Done, you can try again after upgrading. ( pip install --upgrade miyuki )
