### ISSUE TITLE
When the program crawls in batches, it always reports an error of 28. Is there a solution?

### ISSUE THREAD

**Issue by bjbywx** [MiyukiQAQ/MissAV-Downloader#22]
First of all, I would like to thank the author for his selfless dedication
When the program is crawling in batches, it will take a long time to detect whether there are duplicates after disconnection.
When checking whether it has been downloaded, an error of 28 will always be reported. Is there a solution?
grateful.

**Comment by MiyukiQAQ** [comment]
> First of all, I would like to thank the author for his selfless dedication
> 
> When the program is crawling in batches, it will take a long time to detect whether there are duplicates after disconnection.
> 
> When checking whether it has been downloaded, an error of 28 will always be reported. Is there a solution?
> 
> grateful.

Hi, I don't understand what disconnection means. Could you please provide a screenshot of the error report?

**Comment by MiyukiQAQ** [comment]
> First of all, I would like to thank the author for his selfless dedication When the program is crawling in batches, it will take a long time to detect whether there are duplicates after disconnection. When checking whether it has been downloaded, an error of 28 will always be reported. Is there a solution? grateful.

It would be best if you could provide the command where the error occurred.

**Comment by bjbywx** [comment]
ok I need to reproduce the problem, can you speak Chinese?

**Comment by MiyukiQAQ** [comment]
> ok I need to reproduce the problem, can you speak Chinese?

沒問題

**Comment by bjbywx** [comment]
When batch downloading a category, if the download is interrupted due to network fluctuations or other reasons, the task will be re-executed and repeated downloads will be detected. If the detection is too long, the error CURLE_OPERATION_TIMEDOUT (28) will be reported. Please refer to this error, https://curl.se/libcurl/c/libcurl-errors.html.

**Comment by MiyukiQAQ** [comment]
> When batch downloading a category, if the download is interrupted due to network fluctuations or other reasons, the task will be re-executed and repeated downloads will be detected. If the detection is too long, the error CURLE_OPERATION_TIMEDOUT (28) will be reported. Please refer to this error, https://curl.se/libcurl/c/libcurl-errors.html.

You may need a network proxy.

**Comment by bjbywx** [comment]
I have enabled the network proxy. Do I need to set anything in the program?

**Comment by MiyukiQAQ** [comment]
> I have enabled the network proxy. Do I need to set anything in the program?

I can help you with remote desktop

**Comment by MiyukiQAQ** [comment]
> I have enabled the network proxy. Do I need to set anything in the program?

You can leave your contact information and I will contact you

**Comment by bjbywx** [comment]
TG     https://t.me/anzaihao
