### ISSUE TITLE
not working for this specific video

### ISSUE THREAD

**Issue by finitebull** [MiyukiQAQ/MissAV-Downloader#23]
not working for this specific video : https://missav.com/en/vgd-171 , not sure why , the Progress bar is abnormally short , only 27 in size , not like other video which have thousands in size . the result video have zero disk size and cannot be open .
suspect something went wrong in the download period but the error not catched by the programe and then caused ffmpeg to error

## miyuke version:
miyuki-0.3.5
curl-cffi (0.7.3)
cffi (1.17.1)
certifi  (2024.8.30)
typing-extensions  (4.12.2)
pycparser (2.22)

##  ffmpeg version
ffmpeg version N-107046-gc6364b711b-20220604 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
libavutil      57. 26.100 / 57. 26.100
  libavcodec     59. 32.102 / 59. 32.102
  libavformat    59. 24.100 / 59. 24.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 40.100 /  8. 40.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100

### in cmd :
miyuki -proxy localhost:10809 -ffmpeg -urls   https://missav.com/en/vgd-171

 ██████   ██████  ███                        █████       ███
░░██████ ██████  ░░░                        ░░███       ░░░
 ░███░█████░███  ████  █████ ████ █████ ████ ░███ █████ ████
 ░███░░███ ░███ ░░███ ░░███ ░███ ░░███ ░███  ░███░░███ ░░███
 ░███ ░░░  ░███  ░███  ░███ ░███  ░███ ░███  ░██████░   ░███
 ░███      ░███  ░███  ░███ ░███  ░███ ░███  ░███░░███  ░███
 █████     █████ █████ ░░███████  ░░████████ ████ █████ █████
░░░░░     ░░░░░ ░░░░░   ░░░░░███   ░░░░░░░░ ░░░░ ░░░░░ ░░░░░
                        ███ ░███
                       ░░██████
                        ░░░░░░

Miyuki - 2024-11-10 15:20:48 - INFO - Network proxy enabled.
Miyuki - 2024-11-10 15:20:48 - INFO - Processing URL: https://missav.com/en/vgd-171
Miyuki - 2024-11-10 15:20:53 - INFO - Matching uuid successfully: 419c8010-1776-4c62-849b-80fa390558c8
Progress: [##################################################] 27/27
Miyuki - 2024-11-10 15:21:15 - INFO - Complete save jpegs for: miyuki_movies_folder/vgd-171.mp4
Miyuki - 2024-11-10 15:21:15 - INFO - total files count: 27 , found files count: 27
Miyuki - 2024-11-10 15:21:15 - INFO - file integrity is 100.00%
ffmpeg version N-107046-gc6364b711b-20220604 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220604
  libavutil      57. 26.100 / 57. 26.100
  libavcodec     59. 32.102 / 59. 32.102
  libavformat    59. 24.100 / 59. 24.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 40.100 /  8. 40.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[mjpeg @ 000001e1b187eb00] No JPEG data found in image
[image2 @ 000001e1afd695c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b180] No JPEG data found in image
[image2 @ 000001e1b187ea00] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b1895800] No JPEG data found in image
[image2 @ 000001e1b187ea00] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b1895800] No JPEG data found in image
[image2 @ 000001e1b187ea00] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b1895a40] No JPEG data found in image
[image2 @ 000001e1b187ea00] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1afd6dc00] No JPEG data found in image
[image2 @ 000001e1b187ea00] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1afd6dc00] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1afd6dc00] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b140] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b140] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b140] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b140] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b140] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b140] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b140] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b188b140] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b1890680] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b1890680] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b1890680] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b1890680] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b189ee40] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b189ee40] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b189ee40] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b189ee40] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b189ee40] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b189ee40] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[mjpeg @ 000001e1b189ee40] No JPEG data found in image
[image2 @ 000001e1b188c0c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mjpeg @ 000001e1afd6eac0] No JPEG data found in image
[concat @ 000001e1b1862ac0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, concat, from 'input.txt':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 fps, 25 tbr, 25 tbn
[mp4 @ 000001e1afd6db40] dimensions not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times
Miyuki - 2024-11-10 15:21:16 - ERROR - Movie name: vgd-171, FFmpeg execution failed: Command '['ffmpeg', '-f', 'concat', '-safe', '0', '-i', 'input.txt', '-c', 'copy', 'miyuki_movies_folder/vgd-171.mp4']' returned non-zero exit status 1.
Miyuki - 2024-11-10 15:21:16 - ERROR - Failed to download the movie: https://missav.com/en/vgd-171, error: [WinError 87] The parameter is incorrect: 'miyuki_movies_folder/vgd-171.mp4' -> "miyuki_movies_folder/VGD-171 AV actress's behind-the-scenes report: Kaho Shibuya.mp4"

### in miyuki_error.txt :
Time: 2024-11-10 15:27:53 - URL: https://missav.com/en/vgd-171 - Error: [WinError 87] The parameter is incorrect: 'miyuki_movies_folder/vgd-171.mp4' -> "miyuki_movies_folder/VGD-171 AV actress's behind-the-scenes report: Kaho Shibuya.mp4"

**Comment by MiyukiQAQ** [comment]
Thank you for your feedback, the information you provided was very helpful, and this issue has now been fixed.

**Comment by MiyukiQAQ** [comment]
pip install --upgrade miyuki

and try again😀
