### ISSUE TITLE
Archive argument and shorter filename

### ISSUE THREAD

**Issue by snwefly** [MiyukiQAQ/MissAV-Downloader#24]
First of all thanks for the implementing my previous request.

Could you please make a Archive argument to allow to store downloaded list to a text file to avoid future/duplicate downloads?

something similar to yt-dlp -download-archive

Some of the files names are too long getting "[Errno 36]" and filename switched to code only.

can we have the option to grab the shorter filename?

![image](https://github.com/user-attachments/assets/cb4b6279-1013-4d5e-82d8-7fcb29d3e725)

Thanks
Have a good day

**Comment by MiyukiQAQ** [comment]
pip install --upgrade
miyuki -h

You can see the -title option，use this to get full title as the movie file name ( default is code only )

Miyuki will not download duplicate files in the same folder by default.

**Comment by snwefly** [comment]
Thanks for the -title option but long title name still brake the filename

for example /en/skmj-551

even if you use -title file name will endup only as skmj-551.mp4 due to long filename error

![image](https://github.com/user-attachments/assets/4c885a66-d04d-4ae0-b896-9521f0009e3a)

<title> on the webpage is more suitable for file name, could you please make it able to grab that instead of full title name?

>Miyuki will not download duplicate files in the same folder by default.

only if the files are present in the folder, if you delete or move the video files Miyuki will download them once again.

in yt-dlp/gallery-dl you can save the downloaded files url/ID in a text file with -download-archive option so when you use the application will check the archive text list before downloading again.

**Comment by MiyukiQAQ** [comment]
OK, thanks for your suggestion, I will implement it
1. <title> on the webpage is more suitable for file name
2. a new option : use a txt file to record the downloaded URL to avoid repeated downloads

**Comment by MiyukiQAQ** [comment]
> Thanks for the -title option but long title name still brake the filename
> 
> for example /en/skmj-551
> 
> even if you use -title file name will endup only as skmj-551.mp4 due to long filename error
> 
> ![image](https://private-user-images.githubusercontent.com/88805679/385112626-4c885a66-d04d-4ae0-b896-9521f0009e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTE5OTEsIm5iZiI6MTczMTQxMTY5MSwicGF0aCI6Ii84ODgwNTY3OS8zODUxMTI2MjYtNGM4ODVhNjYtZDA0ZC00YWUwLWI4OTYtOTUyMWYwMDA5ZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDExNDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OGMxMTc4OTlkOTIzZmY5YTExMTAxMzg5NTUyYzM1ZWJlODgyNDk4MmI2OGE5ZTkzMWM5OTFmZWMzMDY2MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q4X9KZTkTFLPyLuUCPl1bYevVJ6wZb9MAeMXGx3X8Ek)
> 
> <title> on the webpage is more suitable for file name, could you please make it able to grab that instead of full title name?
> > Miyuki will not download duplicate files in the same folder by default.
> 
> only if the files are present in the folder, if you delete or move the video files Miyuki will download them once again.
> 
> in yt-dlp/gallery-dl you can save the downloaded files url/ID in a text file with -download-archive option so when you use the application will check the archive text list before downloading again.

Currently, a txt file is used by default to record downloaded movies. If a movie has been downloaded, it will not be downloaded again next time. However, the method you mentioned of getting the file name from <title> does not seem to work, because sometimes the string length in <title> is longer than the one I use in my current program.

**Comment by snwefly** [comment]
>Currently, a txt file is used by default to record downloaded movies. If a movie has been downloaded, it will not be downloaded again next time.

Are you talking about the "input.txt" file? because when i use the same url its redownloading the same file again.

Seems like you're using "<h1 class="text-base lg:text-lg text-nord6" to get the movie title and i never came a cross any title is longer than the string you're using.

I noticed that <title> is exactly 55 characters in every single movie, i guess one way to solve the issue is just splice the "<h1 class="text-base lg:text-lg text-nord6" and allow option like -shorttitle.

**Comment by MiyukiQAQ** [comment]
> >Currently, a txt file is used by default to record downloaded movies. If a movie has been downloaded, it will not be downloaded again next time.
> 
> 
> 
> Are you talking about the "input.txt" file? because when i use the same url its redownloading the same file again.
> 
> 
> 
> Seems like you're using "<h1 class="text-base lg:text-lg text-nord6" to get the movie title and i never came a cross any title is longer than the string you're using.
> 
> 
> 
> I noticed that <title> is exactly 55 characters in every single movie, i guess one way to solve the issue is just splice the "<h1 class="text-base lg:text-lg text-nord6" and allow option like -shorttitle.

pip install --upgrade miyuki

**Comment by MiyukiQAQ** [comment]
> >Currently, a txt file is used by default to record downloaded movies. If a movie has been downloaded, it will not be downloaded again next time.
> 
> 
> 
> Are you talking about the "input.txt" file? because when i use the same url its redownloading the same file again.
> 
> 
> 
> Seems like you're using "<h1 class="text-base lg:text-lg text-nord6" to get the movie title and i never came a cross any title is longer than the string you're using.
> 
> 
> 
> I noticed that <title> is exactly 55 characters in every single movie, i guess one way to solve the issue is just splice the "<h1 class="text-base lg:text-lg text-nord6" and allow option like -shorttitle.

If the title is in Traditional Chinese or Simplified Chinese or Japanese, then <title> may be longer.
e.g. https://missav.com/dm26/miab-254-uncensored-leak

**Comment by MiyukiQAQ** [comment]
> >Currently, a txt file is used by default to record downloaded movies. If a movie has been downloaded, it will not be downloaded again next time.
> 
> 
> 
> Are you talking about the "input.txt" file? because when i use the same url its redownloading the same file again.
> 
> 
> 
> Seems like you're using "<h1 class="text-base lg:text-lg text-nord6" to get the movie title and i never came a cross any title is longer than the string you're using.
> 
> 
> 
> I noticed that <title> is exactly 55 characters in every single movie, i guess one way to solve the issue is just splice the "<h1 class="text-base lg:text-lg text-nord6" and allow option like -shorttitle.

Input.txt is for ffmpeg, and miyuki_downloaded_urls.txt is used to record the download history. You need to update miyuki to take effect.

pip install --upgrade miyuki

**Comment by snwefly** [comment]
Forgot to update it sorry. miyuki_downloaded_urls.txt is preset on the working dir. Thanks

>the title is in Traditional Chinese or Simplified Chinese or Japanese, then <title> may be longer. e.g. https://missav.com/dm26/miab-254-uncensored-leak


![image](https://github.com/user-attachments/assets/9fdf6e4c-c180-40ea-b307-994dd824fcbf)


It's got 43 characters and i checked other movies in ja, zh its still got 55 character limit on the title.

Grabing "<h1 class="text-base lg:text-lg text-nord6" is causing the "File name too long" error

for example skmj-551"<h1 class="text-base lg:text-lg text-nord6" character count 
for en 316
for Zh 100
for ja 131

while <title> is 55 characters for all languages.

**Comment by snwefly** [comment]
` match_title_pattern = r'<title>([^"]+)</title>'` instead the old one

is working wonderfully, every file is under 55 char length and no filename error so far.

Its up to you to push it to the main branch or not.

Thanks once again 😁

**Comment by MiyukiQAQ** [comment]
> Forgot to update it sorry. miyuki_downloaded_urls.txt is preset on the working dir. Thanks
> 
> 
> 
> >the title is in Traditional Chinese or Simplified Chinese or Japanese, then <title> may be longer. e.g. https://missav.com/dm26/miab-254-uncensored-leak
> 
> 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/9fdf6e4c-c180-40ea-b307-994dd824fcbf)
> 
> 
> 
> 
> 
> It's got 43 characters and i checked other movies in ja, zh its still got 55 character limit on the title.
> 
> 
> 
> Grabing "<h1 class="text-base lg:text-lg text-nord6" is causing the "File name too long" error
> 
> 
> 
> for example skmj-551"<h1 class="text-base lg:text-lg text-nord6" character count 
> 
> for en 316
> 
> for Zh 100
> 
> for ja 131
> 
> 
> 
> while <title> is 55 characters for all languages.
> 
> 
> 
> 
> 
> Unrelated question: is there any special meaning behind the repo name miyuki? 😁

Miyuki, a game character, from 「Summer Memories」

**Comment by MiyukiQAQ** [comment]
> match_title_pattern = r'<title>([^"]+)</title>' instead the old one

OK, match_title_pattern = r'<title>([^"]+)</title>' instead the old one

**Comment by snwefly** [comment]
> Miyuki, a game character, from 「Summer Memories」


Going to try that game 😁, have a good day.

**Comment by MiyukiQAQ** [comment]
> have a good day.

have a good day  : )
