### ISSUE TITLE
Thank you MiyukiQAQ

### ISSUE THREAD

**Issue by Teleangels** [MiyukiQAQ/MissAV-Downloader#27]
Thank you for the contribution from @MiyukiQAQ. When I compared Missav and Jable, I felt that Jable seemed to have better clarity.
Do you have any intention to create a web crawler for Jable?

**Comment by MiyukiQAQ** [comment]
> Thank you for the contribution from @MiyukiQAQ. When I compared Missav and Jable, I felt that Jable seemed to have better clarity.
> 
> Do you have any intention to create a web crawler for Jable?

I'll try

**Comment by MiyukiQAQ** [comment]
> Thank you for the contribution from @MiyukiQAQ. When I compared Missav and Jable, I felt that Jable seemed to have better clarity. Do you have any intention to create a web crawler for Jable?

I tried the pure python implementation, but after multiple requests, the server would return http403, so selenium should be used. However, there is already a reliable selenium implementation, I recommend you to use this: 
[https://github.com/hcjohn463/JableTVDownload](url)
