### ISSUE TITLE
UUID fetch failed: 403 Forbidden

### ISSUE THREAD

**Issue by gheescoo** [MiyukiQAQ/MissAV-Downloader#4]
Montreal, Canada(我身在古國). Response will be 403 if only user agent of headers is provided.

And thus it cannot find its counterpart uuid

**Comment by MiyukiQAQ** [comment]
Everything is fine here. I recommend using the English version of MissAV, or provide your URL so I can determine why the uuid cannot be found.（or you need proxy）
