### ISSUE TITLE
UnicodeEncodeError How to using correctly?

### ISSUE THREAD

**Issue by Topbcy** [MiyukiQAQ/MissAV-Downloader#8]
Tks for your effect, But I got below this error code, is anything wrong I set?

PS E:\MissAV-Downloader-master> python.exe .\downloader.py
C:\Users\Bcy\AppData\Local\Programs\Python\Python312\Lib\site-packages\paramiko\pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
C:\Users\Bcy\AppData\Local\Programs\Python\Python312\Lib\site-packages\paramiko\transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
process url: https://missav.com/dm39/en/dandy-917
Traceback (most recent call last):
  File "E:\MissAV-Downloader-master\downloader.py", line 287, in <module>
    main(url, scp_action=False)
  File "E:\MissAV-Downloader-master\downloader.py", line 188, in main
    movie_uuid = get_movie_uuid(movie_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\MissAV-Downloader-master\downloader.py", line 86, in get_movie_uuid
    file.write(html)
UnicodeEncodeError: 'cp950' codec can't encode character '\u54b2' in position 1659: illegal multibyte sequence
PS E:\MissAV-Downloader-master>

**Comment by Topbcy** [comment]
I found a issue.
If I using type 3, than mean download from a public playlist url
But only download page 1 , page 2 3 4 5..... wont download. 
Please check about this function.

**Comment by MiyukiQAQ** [comment]
> In downloader.py line 85 , I edited ` with open("movie.html", "w") as file:` to ` with open("movie.html", "w", encoding='UTF-8') as file::`
> 
> and now working fine~

Thank you for the information you provided. The original intention of saving this HTML source code was to facilitate debugging. I didn't expect that there would be an encoding problem.

**Comment by MiyukiQAQ** [comment]
> I found a issue. If I using type 3, than mean download from a public playlist url But only download page 1 , page 2 3 4 5..... wont download. Please check about this function.
> 
> And please help to improve downloader.py Download before please check the movie file existed or not. If does not exist continue download. If existed, skip that movie continue next movie file.



> I found a issue. If I using type 3, than mean download from a public playlist url But only download page 1 , page 2 3 4 5..... wont download. Please check about this function.
> 
> And please help to improve downloader.py Download before please check the movie file existed or not. If does not exist continue download. If existed, skip that movie continue next movie file.

OK, I will first solve the problem of skipping downloading if the movie exists, and then solve the problem of only downloading the first page of the public playlist.

**Comment by Topbcy** [comment]
> > I found a issue. If I using type 3, than mean download from a public playlist url But only download page 1 , page 2 3 4 5..... wont download. Please check about this function.
> > And please help to improve downloader.py Download before please check the movie file existed or not. If does not exist continue download. If existed, skip that movie continue next movie file.
> 
> > I found a issue. If I using type 3, than mean download from a public playlist url But only download page 1 , page 2 3 4 5..... wont download. Please check about this function.
> > And please help to improve downloader.py Download before please check the movie file existed or not. If does not exist continue download. If existed, skip that movie continue next movie file.
> 
> OK, I will first solve the problem of skipping downloading if the movie exists, and then solve the problem of only downloading the first page of the public playlist.

Tks for your effert, This is a very good tools.

**Comment by MiyukiQAQ** [comment]
> > > I found a issue. If I using type 3, than mean download from a public playlist url But only download page 1 , page 2 3 4 5..... wont download. Please check about this function.
> > > And please help to improve downloader.py Download before please check the movie file existed or not. If does not exist continue download. If existed, skip that movie continue next movie file.
> > 
> > 
> > > I found a issue. If I using type 3, than mean download from a public playlist url But only download page 1 , page 2 3 4 5..... wont download. Please check about this function.
> > > And please help to improve downloader.py Download before please check the movie file existed or not. If does not exist continue download. If existed, skip that movie continue next movie file.
> > 
> > 
> > OK, I will first solve the problem of skipping downloading if the movie exists, and then solve the problem of only downloading the first page of the public playlist.
> 
> Tks for your effert, This is a very good tools.

Hello, both issues have been fixed now. You can pull the latest code to test. Currently, if the file already exists, the download will be skipped. For playlists and favorites, the data of the next page will be recursively obtained to ensure that the movie URL of each page is obtained.
